# Generated by Django 5.1.1 on 2024-09-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('date', models.DateField(auto_created=True, default='2020-01-01')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='Missing description')),
                ('results', models.TextField(default='Missing results')),
                ('project_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_boss', to='SIAM.investigator')),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('measure', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='SIAM.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Investigator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='SIAM.investigator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigators', to='SIAM.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_precedent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='SIAM.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedents', to='SIAM.project')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resourceType', models.CharField(max_length=1024)),
                ('data_dir', models.CharField(max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='SIAM.project')),
            ],
        ),
    ]
