# Generated by Django 5.1.1 on 2024-10-03 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350, unique=True)),
                ('acron', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='project_precedent',
            name='precedent',
        ),
        migrations.RemoveField(
            model_name='project_precedent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='measures',
            name='project',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='acron',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='inv_area',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='investigators',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='investigatorlist', to='SIAM.investigator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='measures',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='SIAM.measures'),
        ),
        migrations.AddField(
            model_name='project',
            name='resource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='SIAM.resources'),
        ),
        migrations.AddField(
            model_name='project',
            name='tecnic_boss',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='tecnic_boss', to='SIAM.investigator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_boss',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='project_boss', to='SIAM.investigator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.TextField(default='Still no results'),
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='SIAM.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='entitys',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='entitys', to='SIAM.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='financed',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='financed', to='SIAM.entity'),
        ),
        migrations.AddField(
            model_name='project',
            name='leed_entity',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='leed_entity', to='SIAM.entity'),
        ),
        migrations.DeleteModel(
            name='Project_Investigator',
        ),
        migrations.DeleteModel(
            name='Project_precedent',
        ),
    ]
