# Generated by Django 5.1.1 on 2024-10-03 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAM', '0003_remove_project_clients_remove_project_entitys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='financed',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='financed', to='SIAM.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leed_entity',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='leed_entity', to='SIAM.entity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_boss',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='project_boss', to='SIAM.investigator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnic_boss',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='tecnic_boss', to='SIAM.investigator'),
        ),
    ]
