# Generated by Django 5.1.2 on 2024-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAM', '0005_remove_resources_data_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='princ_img',
            field=models.ImageField(blank='', default='', upload_to='princ_img/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource',
            field=models.ImageField(blank='', default='', upload_to='resources/'),
        ),
    ]
