# Generated by Django 5.1.2 on 2024-10-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAM', '0006_project_princ_img_alter_resources_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='measure',
            field=models.FileField(upload_to='measures/'),
        ),
    ]
